apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: spark-dev
spec:
  type: LoadBalancer  # Use NodePort if LoadBalancer is not required
  ports:
    - port: 4040
      targetPort: 4040
      name: spark-ui
  selector:
    app: spark
    spark-role: driver
    name: {{ .Values.appName }}
