apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  name: notebook-cluster-ip
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  selector:
    app: notebook
  ports:
  - port: 7077 # The port the Spark driver listens on
    name: driver-port
    protocol: TCP
    targetPort: 7077
  - name: driver-rpc-port
    port: 7078
    targetPort: 7078
    protocol: TCP
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079  
  - name: http
    port: 80
    targetPort: 8889
    protocol: TCP
  type: ClusterIP