apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      serviceAccountName: spark
      containers:
      - name: notebook
        image: wenyixu101/all-spark-notebook:spark-3.5.0_2
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "start-notebook.sh"]
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "no"
        - name: NOTEBOOK_ARGS
          value: "--NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True"
