{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role  # Use ClusterRole if you need cluster-wide access
metadata:
  namespace: {{ include "data-platform.role.spark" . }}
  name: {{ include "data-platform.role.spark" . }}
rules: {{ include "data-platform.role.spark" . }}
{{- end }}
