apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-upload-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/spark-uploads"
