kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:3.5.0
          command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
          # env:
          #   - name: SPARK_MASTER_PORT
          #     value: "7077"
          #   - name: SPARK_MASTER_WEBUI_PORT
          #     value: "8080"
          #   - name: SPARK_MASTER_LOG
          #     value: "/spark/logs"
          #   - name: SPARK_WORK_LOAD
          #     value: "master"
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 400m
              memory: 1Gi
            limits:
              cpu: 400m
              memory: 1Gi


